// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXDDMmzJFN-ANvjodGomhS0rOPWwRM8IY',
    appId: '1:475451559097:web:0972b7469c3216c0b25f68',
    messagingSenderId: '475451559097',
    projectId: 'mystery-pixels',
    authDomain: 'mystery-pixels.firebaseapp.com',
    storageBucket: 'mystery-pixels.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3zfYXUczlFrcDgJmRmisZzJxdkGQbcYU',
    appId: '1:475451559097:android:37d178449cd8289db25f68',
    messagingSenderId: '475451559097',
    projectId: 'mystery-pixels',
    storageBucket: 'mystery-pixels.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUg9lOc2Gm7Lyva8tp8TYnoW23XfByYSE',
    appId: '1:475451559097:ios:ee0efaa81d8f041db25f68',
    messagingSenderId: '475451559097',
    projectId: 'mystery-pixels',
    storageBucket: 'mystery-pixels.firebasestorage.app',
    iosBundleId: 'com.example.mysteryPixels',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUg9lOc2Gm7Lyva8tp8TYnoW23XfByYSE',
    appId: '1:475451559097:ios:ee0efaa81d8f041db25f68',
    messagingSenderId: '475451559097',
    projectId: 'mystery-pixels',
    storageBucket: 'mystery-pixels.firebasestorage.app',
    iosBundleId: 'com.example.mysteryPixels',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXDDMmzJFN-ANvjodGomhS0rOPWwRM8IY',
    appId: '1:475451559097:web:fe90dfddb7e3b405b25f68',
    messagingSenderId: '475451559097',
    projectId: 'mystery-pixels',
    authDomain: 'mystery-pixels.firebaseapp.com',
    storageBucket: 'mystery-pixels.firebasestorage.app',
  );
}
